# Site settings
title: A blog about Markel Hoxha Work history
description: A blog about Markel Hoxha Work history
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Markel Hoxha
user_description: I am a Software Engineer and currently, I am doing my master of science in Software Engineering and Management in Heilbronn Germany and I have a Bachelor of Science in Informatics from FSHN University and almost 3 years of software development experience.


I am experienced in web development with Microsoft technologies using C#, .Net Framework, Xamarin Forms, WPF, SQL Server, Asp.Net, Ado.net, Entity Framework, NHIbernate, Angular, Stored Procedures, HTML, CSS, etc.
I have also developed web pages using technologies like AJAX ,JQuery,PHP,Laravel,Javascript,Mysql.


When working on a new project ,i like to speak with my clients so that i can have a better understanding of their needs and vision of the project.
Thank you in advance for your time and consideration .
I look forward to working with you soon.
user_title: Full Stack .Net Developer
email: markel.hoxha4@outlook.com
twitter_username: lorem_ipsum
github_username:  Markelhoxha1
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
